apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: migrator-env
          ports:
            - containerPort: 8081
          command:
            - sh
            - -c
          args:
            - |
              URL="$(printf '%s' "$DATABASE_URL" \
                | sed 's/&uselibpqcompat=true//g' \
                | sed 's/?uselibpqcompat=true&/?/g' \
                | sed 's/?uselibpqcompat=true$//g')"

              echo "Starting pgweb..."
              pgweb --bind=0.0.0.0 --listen=8081 --url "$URL"
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: pgweb
  ports:
    - name: http
      port: 8081
      targetPort: 8081
